version: '2.0'
services:
  zookeeper0:
    build:
      context: .
      dockerfile: zookeeper.Dockerfile
    image: jason/zookeeper:3.4.6
    container_name: zookeeper0
    hostname: zookeeper0
    ports:
      - "12181:12181"
      - "12888:12888"
      - "13888:13888"
    expose:
      - 12181
      - 12888
      - 13888
    environment:
      ZOOKEEPER_PORT: 12181
      ZOOKEEPER_ID: 0
      ZOOKEEPER_SERVERS: server.0=zookeeper0:12888:13888 server.1=zookeeper1:12889:13889 server.2=zookeeper2:12890:13890
  zookeeper1:
    build:
      context: .
      dockerfile: zookeeper.Dockerfile
    image: jason/zookeeper:3.4.6
    container_name: zookeeper1
    hostname: zookeeper1
    ports:
      - "12182:12182"
      - "12889:12889"
      - "13889:13889"
    expose:
      - 12182
      - 12889
      - 13889
    environment:
      ZOOKEEPER_PORT: 12182
      ZOOKEEPER_ID: 1
      ZOOKEEPER_SERVERS: server.0=zookeeper0:12888:13888 server.1=zookeeper1:12889:13889 server.2=zookeeper2:12890:13890
#    depends_on:
#      - zookeeper0
  zookeeper2:
    build:
      context: .
      dockerfile: zookeeper.Dockerfile
    image: jason/zookeeper:3.4.6
    container_name: zookeeper2
    hostname: zookeeper2
    ports:
      - "12183:12183"
      - "12890:12890"
      - "13890:13890"
    expose:
      - 12183
      - 12890
      - 13890
    environment:
      ZOOKEEPER_PORT: 12183
      ZOOKEEPER_ID: 2
      ZOOKEEPER_SERVERS: server.0=zookeeper0:12888:13888 server.1=zookeeper1:12889:13889 server.2=zookeeper2:12890:13890
#    depends_on:
#        - zookeeper1
  kafka0:
    build:
      context: .
      dockerfile: kafka.0.10.1.0.Dockerfile
    image: jason/kafka:0.10.1.0
    container_name: kafka0
    hostname: kafka0
    ports:
      - "19092:19092"
    environment:
      ZOOKEEPER_CONNECT: zookeeper0:12181,zookeeper1:12182,zookeeper2:12183/kafka
      BROKER_ID: 0
      LISTENERS: PLAINTEXT://kafka0:19092
      ZOOKEEPER_SESSION_TIMEOUT: 3600000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
        - zookeeper0
        - zookeeper1
        - zookeeper2
    expose:
      - 9092
#    links:
#      - zookeeper
  kafka1:
    build:
      context: .
      dockerfile: kafka.0.10.1.0.Dockerfile
    image: jason/kafka:0.10.1.0
    container_name: kafka1
    hostname: kafka1
    ports:
      - "19093:19093"
    environment:
      ZOOKEEPER_CONNECT: zookeeper0:12181,zookeeper1:12182,zookeeper2:12183/kafka
      BROKER_ID: 1
      LISTENERS: PLAINTEXT://kafka1:19093
      ZOOKEEPER_SESSION_TIMEOUT: 3600000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
        - zookeeper0
        - zookeeper1
        - zookeeper2
    expose:
      - 9093
#    links:
#      - zookeeper
  kafka2:
    build: .
    build:
      context: .
      dockerfile: kafka.0.10.1.0.Dockerfile
    image: jason/kafka:0.10.1.0
    container_name: kafka2
    hostname: kafka2
    ports:
      - "19094:19094"
    environment:
      ZOOKEEPER_CONNECT: zookeeper0:12181,zookeeper1:12182,zookeeper2:12183/kafka
      BROKER_ID: 2
      LISTENERS: PLAINTEXT://kafka2:19094
      ZOOKEEPER_SESSION_TIMEOUT: 3600000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
        - zookeeper0
        - zookeeper1
        - zookeeper2
    expose:
      - 9094
#   links:
#     - zookeeper